name: kazoo-configs-core
base_branch: origin/master
base_core: null
template: spec.tmpl
package:
  centos7:
    name: kazoo-sounds
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: Audio files for the Kazoo platform
    description: |
      Audio files for the various components that make up the Kazoo platform.
    dist: .el7.centos
    requires:
      sudo: {}
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      %{__mkdir} -p %{buildroot}/usr/share/kazoo-freeswitch/sounds
      %{__mkdir} -p %{buildroot}/opt/kazoo/sounds
      find freeswitch/ -mindepth 1 -maxdepth 1 -type d -exec cp -a {} %{buildroot}/usr/share/kazoo-freeswitch/sounds \;
      find kazoo-core/ -mindepth 1 -maxdepth 1 -type d -exec cp -a {} %{buildroot}/opt/kazoo/sounds \;
    files:
      doc:
        - CHANGELOG
        - VERSION
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
metapackage:
  -
    name: meta-kazoo-applications
    package: kazoo-configs-core
    type: required
    branch: 'master'
